# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ios_derived_data = "#{Dir.pwd}/DerivedData"

default_platform :ios

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    sync_code_signing(
      type:            "development",
      git_url:         "git@github.com:sunggyu-jeong/fastlane-certs.git",
      app_identifier:  "com.moodly.diary.emotion",
      readonly:        true,
      force_for_new_certificates: true
    )
    
    sync_code_signing(
      type:                    "appstore",
      git_url:                 "git@github.com:sunggyu-jeong/fastlane-certs.git",
      app_identifier:          "com.moodly.diary.emotion",
      readonly:                true,
      force_for_new_certificates: true
    )

    if options[:version]
      increment_version_number(
        version_number: options[:version],
        xcodeproj:      "MoodlyFrontend.xcodeproj"
      )
    end

    increment_build_number(xcodeproj: "MoodlyFrontend.xcodeproj")
    build_app(
      workspace: "MoodlyFrontend.xcworkspace",
      scheme:    "MoodlyFrontend",
      configuration: "Release",
      export_method: "app-store",
      derived_data_path: ios_derived_data,
      clean:false
    )
    upload_to_testflight
  end
end